version: '3'
services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: supresecret
      MYSQL_DATABASE: ofac
      MYSQL_USER: ofac
      MYSQL_PASSWORD: secret
  ofac:
    image: moov/ofac:latest
    ports:
      - "8084:8084"
      - "9094:9094"
    environment:
      DATABASE_TYPE: postgres
      MYSQL_ADDRESS: tcp(mysql:3306)
      MYSQL_DATABASE: ofac
      MYSQL_PASSWORD: secret
      MYSQL_USER: ofac
      # Other databases variables
      DB_HOST:
      DB_PORT:
      DB_SSL:
      DB_NAME:
      DB_USER:
      DB_PASSWORD:
    depends_on:
      - mysql
