openapi: 3.0.2
info:
  description: OFAC (Office of Foreign Assets Control) API is designed to facilitate the enforcement of US government economic sanctions programs required by federal law. This project implements a modern REST HTTP API for companies and organizations to obey federal law and use OFAC data in their applications.
  version: v1
  title: OFAC API
  contact:
    url: https://github.com/moov-io/ofac
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:8084
    description: Local development

tags:
  - name: OFAC
    description: Endpoints for searching individuals and corporations which US government enforces economic sanctions against and adding webhook notifications for search criteria.

paths:
  /ping:
    get:
      tags:
        - OFAC
      summary: Ping the OFAC service to check if running
      operationId: ping
      responses:
        '200':
          description: Service is running properly

  # Customer Endpoints
  /customers/{customerId}:
    get:
      tags:
        - OFAC
      summary: Get information about a customer, addresses, alternate names, and their SDN metadata.
      operationId: getCustomer
      parameters:
        - $ref: '#/components/parameters/requestId'
        - name: customerId
          in: path
          description: Customer ID
          required: true
          schema:
            type: string
            example: c3cf0f66
      responses:
        '200':
          description: Customer and associated metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OFACCustomer'
    put:
      tags:
        - OFAC
      summary: Update a Customer's status to add or remove a manual block.
      operationId: updateCustomerStatus
      parameters:
        - $ref: '#/components/parameters/requestId'
        - name: customerId
          in: path
          description: Customer ID
          required: true
          schema:
            type: string
            example: c3cf0f66
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCustomerStatus'
      responses:
        '200':
          description: Customer status updated
  /customers/{customerId}/watch:
    post:
      tags:
        - OFAC
      summary: Add OFAC watch on a Customer
      operationId: addCustomerWatch
      parameters:
        - $ref: '#/components/parameters/requestId'
        - name: customerId
          in: path
          description: Customer ID
          required: true
          schema:
            type: string
            example: c3cf0f66
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WatchRequest'
      responses:
        '200':
          description: Customer watch added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Watch'
        '404':
          description: Customer not found
  /customers/{customerId}/watch/{watchId}:
    delete:
      tags:
        - OFAC
      summary: Remove customer watch
      operationId: removeCustomerWatch
      parameters:
        - $ref: '#/components/parameters/requestId'
        - name: customerId
          in: path
          description: Customer ID
          required: true
          schema:
            type: string
            example: c3cf0f66
        - name: watchId
          in: path
          description: Watch ID, used to identify a specific watch
          required: true
          schema:
            type: string
            example: 0c5e215c
      responses:
        '200':
          description: Customer watch removed
  /customers/watch:
    post:
      tags:
        - OFAC
      summary: Add customer watch by name
      operationId: addCustomerNameWatch
      parameters:
        - $ref: '#/components/parameters/requestId'
        - name: name
          in: query
          required: true
          description: Individual name used to match and send watch notifications
          schema:
            type: string
            example: Jane Smith
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WatchRequest'
      responses:
        '200':
          description: Customer watch applied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Watch'
  /customers/watch/{watchId}:
    delete:
      tags:
        - OFAC
      summary: Remove a Customer name watch
      operationId: removeCustomerNameWatch
      parameters:
        - $ref: '#/components/parameters/requestId'
        - name: watchId
          in: path
          description: Watch ID, used to identify a specific watch
          required: true
          schema:
            type: string
            example: 0c5e215c
        - name: name
          in: query
          description: Customer or Company name watch
          required: true
          schema:
            type: string
            example: Jane Smith
      responses:
        '200':
          description: Company or Customer watch removed

  # Company endpoints

  # SDN Endpoints
  /sdn/{sdnId}:
    get:
      tags:
        - OFAC
      summary: Specially designated national
      operationId: getSDN
      parameters:
        - $ref: '#/components/parameters/requestId'
        - in: path
          name: sdnId
          required: true
          description: SDN ID
          schema:
            type: string
            example: 564dd7d1
      responses:
        '200':
          description: SDN metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SDN'
  /sdn/{sdnId}/alts:
    get:
      tags:
        - OFAC
      summary: Get alternate names for a given SDN
      operationId: getSDNAltNames
      parameters:
        - $ref: '#/components/parameters/requestId'
        - in: path
          name: sdnId
          description: SDN ID
          required: true
          schema:
            type: string
            example: 564dd7d1
      responses:
        '200':
          description: SDN alternate names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SDNAltNames'
  /sdn/{sdnId}/addresses:
    get:
      tags:
        - OFAC
      summary: Get addresses for a given SDN
      operationId: getSDNAddresses
      parameters:
        - $ref: '#/components/parameters/requestId'
        - in: path
          name: sdnId
          description: SDN ID
          required: true
          schema:
            type: string
            example: 564dd7d1
      responses:
        '200':
          description: SDN addresses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Addresses'
  # Search Endpoint
  /search:
    get:
      tags:
        - OFAC
      summary: Search SDN names and metadata
      operationId: searchSDNs
      parameters:
        - $ref: '#/components/parameters/requestId'
        - name: name
          in: query
          schema:
            type: string
            example: Jane Smith
          description: Name which could correspond to a human on the SDN list
        - name: address
          in: query
          schema:
            type: string
            example: 123 83rd Ave
          description: Phsical address which could correspond to a human on the SDN list
        - name: altName
          in: query
          schema:
            type: string
            example: Jane Smith
          description: Alternate name which could correspond to a human on the SDN list
        - name: limit
          in: query
          schema:
            type: integer
            example: 25
          description: Maximum results returned by a search
      responses:
        '200':
          description: SDNs returned from a search
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Search'

  # Downloads endpoint
  /downloads:
    get:
      tags:
        - OFAC
      summary: Return list of recent re-downloads of OFAC data
      operationId: getLatestDownloads
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            example: 25
          description: Maximum results returned by a search
      responses:
        '200':
          description: Recent timestamps and counts of parsed objects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Downloads'

components:
  schemas:
    OFACCustomer:
      description: OFAC Customer and metadata
      properties:
        id:
          description: OFAC Customer ID
          type: string
          example: 9574756b
        SDN:
          $ref: '#/components/schemas/SDN'
        Addresses:
          type: array
          items:
            $ref: '#/components/schemas/Address'
        Alts:
          type: array
          items:
            $ref: '#/components/schemas/Alt'
    SDN:
      description: Specially designated national from OFAC list
      properties:
        entityID:
          type: string
          example: 1231
        sdnName:
          type: string
          example: BANCO NACIONAL DE CUBA
        sdnType:
          type: string
          example: individual
        program:
          type: string
          example: CUBA
        title:
          type: string
          example: Title of an individual
        remarks:
          type: string
        match:
          type: number
          example: 0.91
          description: Remarks on SDN and often additional information about the SDN
    Addresses:
      type: array
      items:
        $ref: '#/components/schemas/Address'
    Address:
      description: Physical address from OFAC list
      properties:
        entityID:
          type: string
          example: 2112
        addressID:
          type: string
          example: 201
        address:
          type: string
          example: 123 73th St
        cityStateProvincePostalCode:
          type: string
          example: Tokyo 103
        country:
          type: string
          example: Japan
        match:
          type: number
          example: 0.91
    SDNAltNames:
      type: array
      items:
        $ref: '#/components/schemas/Alt'
    Alt:
      description: Alternate name from OFAC list
      properties:
        entityID:
          type: string
          example: 306
        alternateID:
          type: string
          example: 220
        alternateType:
          type: string
          example: aka
        alternateName:
          type: string
          example: NATIONAL BANK OF CUBA
        match:
          type: number
          example: 0.91
    UpdateCustomerStatus:
      description: Request body to update a customers status.
      properties:
        status:
          description: manual customer sanction status
          type: string
          enum:
            - Blocked
            - Unblocked
    Search:
      description: Search results containing SDNs, alternate names and/or addreses
      properties:
        SDNs:
          type: array
          items:
            $ref: '#/components/schemas/SDN'
        altNames:
          type: array
          items:
            $ref: '#/components/schemas/Alt'
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/Address'
    Watch:
      description: Customer or Company watch
      properties:
        id:
          description: Object representing a customer or company watch
          type: string
          example: 08ddba92
    WatchRequest:
      description: Webhook or other means of notification on search criteria. OFAC will make a POST request with a body of the customer (SDN, AltNames, and Address).
      properties:
        authToken:
          description: Private token supplied by clients to be used for authenticating webhooks.
          type: string
          example: 75d0384b-a105-4048-9fce-91a280ce7337
        webhook:
          description: HTTPS url for webhook on search match
          type: string
          example: https://api.example.com/ofac/webhook
      required:
        - authToken
        - webhook
    Downloads:
      type: array
      items:
        $ref: '#/components/schemas/Download'
    Download:
      description: Metadata and stats about downloaded OFAC data
      properties:
        SDNs:
          type: integer
          example: 7414
        altNames:
          type: integer
          example: 9729
        addresses:
          type: integer
          example: 11747
        timestamp:
          type: string
          format: date-time
          example: 2006-01-02T15:04:05Z07:00
  parameters:
    requestId:
      in: header
      name: X-Request-Id
      description: Optional Request ID allows application developer to trace requests through the systems logs
      schema:
        type: string
        example: 94c825ee
